### ISSUE TITLE
Bot fails to add Task to Todoist

### ISSUE THREAD

**Issue by tobikrs** [martosaur/todoist_bot#6]
The bot replys on any message with "Something went terribly wrong 😢 Let's maybe try again?" and isn't able to create a task with that message at todoist.

Messages I sent was "Test".

Expected behavior:
- Task gets added to todoist
- Reply: "Task added"

Is someone experience the same behavior? Any idea to fix it?

**Comment by martosaur** [comment]
Hi @tobikrs! Thanks for reporting this. Yeah, Todoist deprecated their v8 API, so the bot had to migrate to v9.

I've just deployed the fix, so it should be fixed now.
