### ISSUE TITLE
Deprecated Todoist API endpoint

### ISSUE THREAD

**Issue by PotHix** [martosaur/todoist_bot#8]
This project is [using the `items/add` endpoint](https://github.com/martosaur/todoist_bot/blob/master/lib/todoist_api/todoist_api.ex#L34), which [is deprecated](https://developer.todoist.com/sync/v9/#add-an-item-without-sync-workflow) and will be removed soon. 

The endpoint is not fully functional, and we decided to remove it to avoid causing more problems. We suggest moving to the [REST API create task endpoint](https://developer.todoist.com/rest/v2/#create-a-new-task), which is quite similar and handles better the needs of this project.

Please let me know if you need any extra information.

**Comment by martosaur** [comment]
Hi @PotHix ! Thank you so much for the heads up! Somehow I wasn't subscribed to my own repo notifications and missed this issue, so was reminded by the bot's users 🤦  it is fixed now!
